### PR TITLE
Show QuickActions "Previous" and "Next" while displaying a ticket found by the current search

### PR DESCRIPTION
**Pull request by Al2Klimov**

### CODE REVIEW

**Comment by mxhash** [comment]
Hi,

can we pull the actions out of

    PageMenu()->child('search')->child('tickets');

Cause some links get prepared on *share/html/Elements/Tabs:878*

**Comment by Al2Klimov** [comment]
No, I don't think so – at least something doesn't work. I'll consult you tomorrow.

**Review by mxhash — APPROVED** [review]
Looks good, thanks!

**Comment by Al2Klimov** [comment]
Closing in favor of #7

**Pull request closed without merging**
